### ISSUE TITLE
Plug-in not working after upgrade

### ISSUE THREAD

**Issue by ReneSelles** [JanJaapKo/DysonPureLink#46]
Hi Jan-Jaap,
Since my last upgrade to Debian 11 the Dyson Pure Link plugin does not work anymore.
The Domoticz error log is below.
I've tried updating the plug-in and reinstall crypto but ik still won't work.

It looks like the Python Crypto module is not working anymore.
It seems that pycrypto has a vulnerability. Maybe it is blocked in the latest release (3.9) of Python.
pycryptodome is a drop-in replacement.

Could you have a look please?

Thanks in advance.

Domoticz version: 2022.2 (build 14742)
Debian 11 (Bullseye)

2022-11-21 19:53:11.611 Error: Dyson slaapkamer: (DysonPureLink) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/DysonPureLink/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: Traceback (most recent call last):
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: File "/home/pi/domoticz/plugins/DysonPureLink/plugin.py", line 77, in <module>
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: from dyson_pure_link_device import DysonPureLinkDevice
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: File "/home/pi/domoticz/plugins/DysonPureLink/dyson_pure_link_device.py", line 3, in <module>
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: import commands
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: File "/home/pi/domoticz/plugins/DysonPureLink/commands.py", line 4, in <module>
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: from cloud.exceptions import DysonInvalidTargetTemperatureException as DITTE
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: File "/home/pi/domoticz/plugins/DysonPureLink/cloud/__init__.py", line 3, in <module>
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: from .account import DysonAccount, DysonAccountCN # noqa: F401
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: File "/home/pi/domoticz/plugins/DysonPureLink/cloud/account.py", line 18, in <module>
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: from .device_info import DysonDeviceInfo
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: File "/home/pi/domoticz/plugins/DysonPureLink/cloud/device_info.py", line 3, in <module>
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: from .utils import decrypt_password
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: File "/home/pi/domoticz/plugins/DysonPureLink/cloud/utils.py", line 9, in <module>
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: from Crypto import Cipher
2022-11-21 19:53:11.613 Error: Dyson slaapkamer: ModuleNotFoundError: No module named 'Crypto'

**Comment by ReneSelles** [comment]
Ok, fixed it myself...
sudo pip3 uninstall crypto
sudo pip3 install pycryptodome
